### ISSUE TITLE
Skins disappear when restart

### ISSUE THREAD

**Issue by lazhiyi** [TeKGameR950/SkinChanger#1]
Can you fix this?I really like this plugin!
sponge7.1.0
minecraft1.12.2
on-line mode=false

**Comment by TeKGameR950** [comment]
Hi, this is not an issue, skins aren't saved after a restart as i didn't added a config file for now.

**Comment by lazhiyi** [comment]
I know now ,thank you.
There's another question,does another player see my skin on server?
I have a minecraft account ,but they may don't.

**Comment by TeKGameR950** [comment]
Yeah, they will see it.

**Comment by lazhiyi** [comment]
thank you!
